# plugin.yml - This is like the plugin's ID card! It tells the Minecraft server what our plugin is called, who made it, and what commands it adds.
# Without this file, the server won't know about SecureAuth at all. Put this in the 'resources' folder of your project.
name: SecureAuth
version: 1.0
main: com.excrele.SecureAuth  # Points to our main Java class - the brain of the plugin!
api-version: 1.20  # Works with Minecraft 1.20 and newer servers. Change if your server is older!
author: excrele  # That's you (or me, the dev)! Credits where due.
description: A super secure login system for cracked Minecraft servers. Premium players log in fast, cracked ones register a password!

# Commands: These are the magic words players type in chat, like /register or /login.
commands:
  register:
    description: Registers a new account with a secure password. Only for first-time cracked players!
    usage: /register <password> <repeat-password>  # How to use it - shows if they mess up.
    permission: secureauth.register  # Who can use this? We'll set defaults below.
  login:
    description: Logs you in with your saved password. Keeps your account safe from impersonators!
    usage: /login <password>
    permission: secureauth.login
  changepass:
    description: Change your current password to a new one (must be logged in!).
    usage: /changepass <old-password> <new-password> <repeat-new-password>
    permission: secureauth.changepass
  setpass:
    description: Admin only: Force-set a player's password (resets it securely).
    usage: /setpass <player-name> <new-password>
    permission: secureauth.setpass
  auth:
    description: Admin commands for managing SecureAuth.
    usage: /auth <subcommand>
    permission: secureauth.admin
  authinfo:
    description: View your account information.
    usage: /authinfo
    permission: secureauth.info
  logout:
    description: Logout from your current session.
    usage: /logout
    permission: secureauth.logout
  logoutall:
    description: Logout from all sessions.
    usage: /logoutall
    permission: secureauth.logout
  2fa:
    description: Manage your 2FA settings.
    usage: /2fa <setup|disable|verify>
    permission: secureauth.2fa
  2faverify:
    description: Verify your 2FA code after login.
    usage: /2faverify <code>
    permission: secureauth.2fa

# Permissions: Like VIP passes. 'default: true' means everyone gets it unless an admin says no.
permissions:
  secureauth.register:
    description: Lets players create a new account.
    default: true  # New players need this!
  secureauth.login:
    description: Lets players log in to their account.
    default: true  # Everyone should be able to!
  secureauth.changepass:
    description: Lets players change their own password.
    default: true  # Handy for updates!
  secureauth.setpass:
    description: Lets admins reset a player's password.
    default: op  # Only server operators get this by default.
  secureauth.bypass:
    description: Skips login checks for trusted staff (like ops/admins). Use wisely!
    default: op  # Only server operators get this by default.
  secureauth.admin:
    description: Access to admin commands for SecureAuth.
    default: op
  secureauth.info:
    description: View your own account information.
    default: true
  secureauth.logout:
    description: Logout from sessions.
    default: true
  secureauth.2fa:
    description: Use 2FA commands.
    default: true